# @package __global__

classifier_free_guidance:
  training_dropout: 0.3
  inference_coef: 3.0

attribute_dropout:
  text: {}
  wav: {}

fuser:
  cross_attention_pos_emb: false
  cross_attention_pos_emb_scale: 0.1
  sum: []
  prepend: []
  cross: [description]
  input_interpolate: []

conditioners:
  description:
    model: clap
    clap:
      checkpoint: /work/u2614323/code/audiocraft-origin/rakec/clap/music_audioset_epoch_15_esc_90.14.pt
      model_arch: "HTSAT-base"
      enable_fusion: false
      sample_rate: 48000
      max_audio_length: 8
      audio_stride: 1
      dim: 512
      attribute: description
      normalize: true
      reduce: false

dataset:
  joint_embed_attributes: [description]
