# @package __global__

datasource:
  max_sample_rate: 44100
  max_channels: 2

  train: egs/clap_ytcharts/train
  valid: egs/clap_ytcharts/test
  evaluate: egs/clap_ytcharts/test
  generate: egs/clap_ytcharts/test # identical to evaluate
