# @package __global__

datasource:
  max_sample_rate: 44100
  max_channels: 2

  train: egs/clap_spotify/train
  valid: egs/clap_spotify/valid
  evaluate: egs/clap_spotify/valid
  generate: egs/clap_spotify/valid