# @package __global__

datasource:
  max_sample_rate: 32000
  max_channels: 2

  train: egs/clap_ytcharts/train
  test: egs/clap_ytcharts/valid
  evaluate: egs/clap_ytcharts/valid
  generate: egs/clap_ytcharts/valid
